























.build/mega2560/Servo/Servo.o : /usr/share/arduino/libraries/Servo/Servo.cpp
	@echo [93mServo/Servo.cpp[0m
	@mkdir -p .build/mega2560/Servo
	@/usr/bin/avr-g++ -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=100 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/mega -I/usr/share/arduino/libraries/Servo -Ilib/ros_lib -Ilib/ros_lib/tests -Ilib/ros_lib/ros_rl500xa -Ilib/ros_lib/std_msgs -Ilib/ros_lib/rosserial_msgs -Ilib/ros_lib/ros -Ilib/ros_lib/tf -Ilib/ros_lib/diagnostic_msgs -Ilib/ros_lib/nav_msgs -Ilib/ros_lib/sensor_msgs -Ilib/ros_lib/rosserial_arduino -Ilib/ros_lib/geometry_msgs -Ilib/ros_lib/tests/time_test -Ilib/ros_lib/tests/array_test -Ilib/ros_lib/tests/float64_test -I/usr/share/arduino/hardware/arduino/cores/arduino -fno-exceptions  -o $@ -c /usr/share/arduino/libraries/Servo/Servo.cpp
include .build/mega2560/Servo/Servo.d



.build/mega2560/Servo/libServo.a : .build/mega2560/Servo/Servo.o
	@echo [92mLinking libServo.a[0m
	@/usr/bin/avr-ar rcs $@ $^












.build/mega2560/ros_lib/time.o : lib/ros_lib/time.cpp
	@echo [93mros_lib/time.cpp[0m
	@mkdir -p .build/mega2560/ros_lib
	@/usr/bin/avr-g++ -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=100 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/mega -I/usr/share/arduino/libraries/Servo -Ilib/ros_lib -Ilib/ros_lib/tests -Ilib/ros_lib/ros_rl500xa -Ilib/ros_lib/std_msgs -Ilib/ros_lib/rosserial_msgs -Ilib/ros_lib/ros -Ilib/ros_lib/tf -Ilib/ros_lib/diagnostic_msgs -Ilib/ros_lib/nav_msgs -Ilib/ros_lib/sensor_msgs -Ilib/ros_lib/rosserial_arduino -Ilib/ros_lib/geometry_msgs -Ilib/ros_lib/tests/time_test -Ilib/ros_lib/tests/array_test -Ilib/ros_lib/tests/float64_test -I/usr/share/arduino/hardware/arduino/cores/arduino -fno-exceptions  -o $@ -c lib/ros_lib/time.cpp
include .build/mega2560/ros_lib/time.d

.build/mega2560/ros_lib/duration.o : lib/ros_lib/duration.cpp
	@echo [93mros_lib/duration.cpp[0m
	@mkdir -p .build/mega2560/ros_lib
	@/usr/bin/avr-g++ -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=100 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/mega -I/usr/share/arduino/libraries/Servo -Ilib/ros_lib -Ilib/ros_lib/tests -Ilib/ros_lib/ros_rl500xa -Ilib/ros_lib/std_msgs -Ilib/ros_lib/rosserial_msgs -Ilib/ros_lib/ros -Ilib/ros_lib/tf -Ilib/ros_lib/diagnostic_msgs -Ilib/ros_lib/nav_msgs -Ilib/ros_lib/sensor_msgs -Ilib/ros_lib/rosserial_arduino -Ilib/ros_lib/geometry_msgs -Ilib/ros_lib/tests/time_test -Ilib/ros_lib/tests/array_test -Ilib/ros_lib/tests/float64_test -I/usr/share/arduino/hardware/arduino/cores/arduino -fno-exceptions  -o $@ -c lib/ros_lib/duration.cpp
include .build/mega2560/ros_lib/duration.d



.build/mega2560/ros_lib/libros_lib.a : .build/mega2560/ros_lib/time.o .build/mega2560/ros_lib/duration.o
	@echo [92mLinking libros_lib.a[0m
	@/usr/bin/avr-ar rcs $@ $^







.build/mega2560/arduino/wiring_shift.o : /usr/share/arduino/hardware/arduino/cores/arduino/wiring_shift.c
	@echo [93marduino/wiring_shift.c[0m
	@mkdir -p .build/mega2560/arduino
	@/usr/bin/avr-gcc -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=100 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/mega -I/usr/share/arduino/libraries/Servo -Ilib/ros_lib -Ilib/ros_lib/tests -Ilib/ros_lib/ros_rl500xa -Ilib/ros_lib/std_msgs -Ilib/ros_lib/rosserial_msgs -Ilib/ros_lib/ros -Ilib/ros_lib/tf -Ilib/ros_lib/diagnostic_msgs -Ilib/ros_lib/nav_msgs -Ilib/ros_lib/sensor_msgs -Ilib/ros_lib/rosserial_arduino -Ilib/ros_lib/geometry_msgs -Ilib/ros_lib/tests/time_test -Ilib/ros_lib/tests/array_test -Ilib/ros_lib/tests/float64_test -I/usr/share/arduino/hardware/arduino/cores/arduino   -o $@ -c /usr/share/arduino/hardware/arduino/cores/arduino/wiring_shift.c
include .build/mega2560/arduino/wiring_shift.d

.build/mega2560/arduino/wiring.o : /usr/share/arduino/hardware/arduino/cores/arduino/wiring.c
	@echo [93marduino/wiring.c[0m
	@mkdir -p .build/mega2560/arduino
	@/usr/bin/avr-gcc -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=100 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/mega -I/usr/share/arduino/libraries/Servo -Ilib/ros_lib -Ilib/ros_lib/tests -Ilib/ros_lib/ros_rl500xa -Ilib/ros_lib/std_msgs -Ilib/ros_lib/rosserial_msgs -Ilib/ros_lib/ros -Ilib/ros_lib/tf -Ilib/ros_lib/diagnostic_msgs -Ilib/ros_lib/nav_msgs -Ilib/ros_lib/sensor_msgs -Ilib/ros_lib/rosserial_arduino -Ilib/ros_lib/geometry_msgs -Ilib/ros_lib/tests/time_test -Ilib/ros_lib/tests/array_test -Ilib/ros_lib/tests/float64_test -I/usr/share/arduino/hardware/arduino/cores/arduino   -o $@ -c /usr/share/arduino/hardware/arduino/cores/arduino/wiring.c
include .build/mega2560/arduino/wiring.d

.build/mega2560/arduino/wiring_analog.o : /usr/share/arduino/hardware/arduino/cores/arduino/wiring_analog.c
	@echo [93marduino/wiring_analog.c[0m
	@mkdir -p .build/mega2560/arduino
	@/usr/bin/avr-gcc -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=100 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/mega -I/usr/share/arduino/libraries/Servo -Ilib/ros_lib -Ilib/ros_lib/tests -Ilib/ros_lib/ros_rl500xa -Ilib/ros_lib/std_msgs -Ilib/ros_lib/rosserial_msgs -Ilib/ros_lib/ros -Ilib/ros_lib/tf -Ilib/ros_lib/diagnostic_msgs -Ilib/ros_lib/nav_msgs -Ilib/ros_lib/sensor_msgs -Ilib/ros_lib/rosserial_arduino -Ilib/ros_lib/geometry_msgs -Ilib/ros_lib/tests/time_test -Ilib/ros_lib/tests/array_test -Ilib/ros_lib/tests/float64_test -I/usr/share/arduino/hardware/arduino/cores/arduino   -o $@ -c /usr/share/arduino/hardware/arduino/cores/arduino/wiring_analog.c
include .build/mega2560/arduino/wiring_analog.d

.build/mega2560/arduino/WInterrupts.o : /usr/share/arduino/hardware/arduino/cores/arduino/WInterrupts.c
	@echo [93marduino/WInterrupts.c[0m
	@mkdir -p .build/mega2560/arduino
	@/usr/bin/avr-gcc -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=100 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/mega -I/usr/share/arduino/libraries/Servo -Ilib/ros_lib -Ilib/ros_lib/tests -Ilib/ros_lib/ros_rl500xa -Ilib/ros_lib/std_msgs -Ilib/ros_lib/rosserial_msgs -Ilib/ros_lib/ros -Ilib/ros_lib/tf -Ilib/ros_lib/diagnostic_msgs -Ilib/ros_lib/nav_msgs -Ilib/ros_lib/sensor_msgs -Ilib/ros_lib/rosserial_arduino -Ilib/ros_lib/geometry_msgs -Ilib/ros_lib/tests/time_test -Ilib/ros_lib/tests/array_test -Ilib/ros_lib/tests/float64_test -I/usr/share/arduino/hardware/arduino/cores/arduino   -o $@ -c /usr/share/arduino/hardware/arduino/cores/arduino/WInterrupts.c
include .build/mega2560/arduino/WInterrupts.d

.build/mega2560/arduino/wiring_digital.o : /usr/share/arduino/hardware/arduino/cores/arduino/wiring_digital.c
	@echo [93marduino/wiring_digital.c[0m
	@mkdir -p .build/mega2560/arduino
	@/usr/bin/avr-gcc -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=100 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/mega -I/usr/share/arduino/libraries/Servo -Ilib/ros_lib -Ilib/ros_lib/tests -Ilib/ros_lib/ros_rl500xa -Ilib/ros_lib/std_msgs -Ilib/ros_lib/rosserial_msgs -Ilib/ros_lib/ros -Ilib/ros_lib/tf -Ilib/ros_lib/diagnostic_msgs -Ilib/ros_lib/nav_msgs -Ilib/ros_lib/sensor_msgs -Ilib/ros_lib/rosserial_arduino -Ilib/ros_lib/geometry_msgs -Ilib/ros_lib/tests/time_test -Ilib/ros_lib/tests/array_test -Ilib/ros_lib/tests/float64_test -I/usr/share/arduino/hardware/arduino/cores/arduino   -o $@ -c /usr/share/arduino/hardware/arduino/cores/arduino/wiring_digital.c
include .build/mega2560/arduino/wiring_digital.d

.build/mega2560/arduino/wiring_pulse.o : /usr/share/arduino/hardware/arduino/cores/arduino/wiring_pulse.c
	@echo [93marduino/wiring_pulse.c[0m
	@mkdir -p .build/mega2560/arduino
	@/usr/bin/avr-gcc -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=100 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/mega -I/usr/share/arduino/libraries/Servo -Ilib/ros_lib -Ilib/ros_lib/tests -Ilib/ros_lib/ros_rl500xa -Ilib/ros_lib/std_msgs -Ilib/ros_lib/rosserial_msgs -Ilib/ros_lib/ros -Ilib/ros_lib/tf -Ilib/ros_lib/diagnostic_msgs -Ilib/ros_lib/nav_msgs -Ilib/ros_lib/sensor_msgs -Ilib/ros_lib/rosserial_arduino -Ilib/ros_lib/geometry_msgs -Ilib/ros_lib/tests/time_test -Ilib/ros_lib/tests/array_test -Ilib/ros_lib/tests/float64_test -I/usr/share/arduino/hardware/arduino/cores/arduino   -o $@ -c /usr/share/arduino/hardware/arduino/cores/arduino/wiring_pulse.c
include .build/mega2560/arduino/wiring_pulse.d






.build/mega2560/arduino/CDC.o : /usr/share/arduino/hardware/arduino/cores/arduino/CDC.cpp
	@echo [93marduino/CDC.cpp[0m
	@mkdir -p .build/mega2560/arduino
	@/usr/bin/avr-g++ -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=100 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/mega -I/usr/share/arduino/libraries/Servo -Ilib/ros_lib -Ilib/ros_lib/tests -Ilib/ros_lib/ros_rl500xa -Ilib/ros_lib/std_msgs -Ilib/ros_lib/rosserial_msgs -Ilib/ros_lib/ros -Ilib/ros_lib/tf -Ilib/ros_lib/diagnostic_msgs -Ilib/ros_lib/nav_msgs -Ilib/ros_lib/sensor_msgs -Ilib/ros_lib/rosserial_arduino -Ilib/ros_lib/geometry_msgs -Ilib/ros_lib/tests/time_test -Ilib/ros_lib/tests/array_test -Ilib/ros_lib/tests/float64_test -I/usr/share/arduino/hardware/arduino/cores/arduino -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/cores/arduino/CDC.cpp
include .build/mega2560/arduino/CDC.d

.build/mega2560/arduino/HID.o : /usr/share/arduino/hardware/arduino/cores/arduino/HID.cpp
	@echo [93marduino/HID.cpp[0m
	@mkdir -p .build/mega2560/arduino
	@/usr/bin/avr-g++ -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=100 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/mega -I/usr/share/arduino/libraries/Servo -Ilib/ros_lib -Ilib/ros_lib/tests -Ilib/ros_lib/ros_rl500xa -Ilib/ros_lib/std_msgs -Ilib/ros_lib/rosserial_msgs -Ilib/ros_lib/ros -Ilib/ros_lib/tf -Ilib/ros_lib/diagnostic_msgs -Ilib/ros_lib/nav_msgs -Ilib/ros_lib/sensor_msgs -Ilib/ros_lib/rosserial_arduino -Ilib/ros_lib/geometry_msgs -Ilib/ros_lib/tests/time_test -Ilib/ros_lib/tests/array_test -Ilib/ros_lib/tests/float64_test -I/usr/share/arduino/hardware/arduino/cores/arduino -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/cores/arduino/HID.cpp
include .build/mega2560/arduino/HID.d

.build/mega2560/arduino/Tone.o : /usr/share/arduino/hardware/arduino/cores/arduino/Tone.cpp
	@echo [93marduino/Tone.cpp[0m
	@mkdir -p .build/mega2560/arduino
	@/usr/bin/avr-g++ -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=100 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/mega -I/usr/share/arduino/libraries/Servo -Ilib/ros_lib -Ilib/ros_lib/tests -Ilib/ros_lib/ros_rl500xa -Ilib/ros_lib/std_msgs -Ilib/ros_lib/rosserial_msgs -Ilib/ros_lib/ros -Ilib/ros_lib/tf -Ilib/ros_lib/diagnostic_msgs -Ilib/ros_lib/nav_msgs -Ilib/ros_lib/sensor_msgs -Ilib/ros_lib/rosserial_arduino -Ilib/ros_lib/geometry_msgs -Ilib/ros_lib/tests/time_test -Ilib/ros_lib/tests/array_test -Ilib/ros_lib/tests/float64_test -I/usr/share/arduino/hardware/arduino/cores/arduino -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/cores/arduino/Tone.cpp
include .build/mega2560/arduino/Tone.d

.build/mega2560/arduino/Stream.o : /usr/share/arduino/hardware/arduino/cores/arduino/Stream.cpp
	@echo [93marduino/Stream.cpp[0m
	@mkdir -p .build/mega2560/arduino
	@/usr/bin/avr-g++ -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=100 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/mega -I/usr/share/arduino/libraries/Servo -Ilib/ros_lib -Ilib/ros_lib/tests -Ilib/ros_lib/ros_rl500xa -Ilib/ros_lib/std_msgs -Ilib/ros_lib/rosserial_msgs -Ilib/ros_lib/ros -Ilib/ros_lib/tf -Ilib/ros_lib/diagnostic_msgs -Ilib/ros_lib/nav_msgs -Ilib/ros_lib/sensor_msgs -Ilib/ros_lib/rosserial_arduino -Ilib/ros_lib/geometry_msgs -Ilib/ros_lib/tests/time_test -Ilib/ros_lib/tests/array_test -Ilib/ros_lib/tests/float64_test -I/usr/share/arduino/hardware/arduino/cores/arduino -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/cores/arduino/Stream.cpp
include .build/mega2560/arduino/Stream.d

.build/mega2560/arduino/WMath.o : /usr/share/arduino/hardware/arduino/cores/arduino/WMath.cpp
	@echo [93marduino/WMath.cpp[0m
	@mkdir -p .build/mega2560/arduino
	@/usr/bin/avr-g++ -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=100 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/mega -I/usr/share/arduino/libraries/Servo -Ilib/ros_lib -Ilib/ros_lib/tests -Ilib/ros_lib/ros_rl500xa -Ilib/ros_lib/std_msgs -Ilib/ros_lib/rosserial_msgs -Ilib/ros_lib/ros -Ilib/ros_lib/tf -Ilib/ros_lib/diagnostic_msgs -Ilib/ros_lib/nav_msgs -Ilib/ros_lib/sensor_msgs -Ilib/ros_lib/rosserial_arduino -Ilib/ros_lib/geometry_msgs -Ilib/ros_lib/tests/time_test -Ilib/ros_lib/tests/array_test -Ilib/ros_lib/tests/float64_test -I/usr/share/arduino/hardware/arduino/cores/arduino -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/cores/arduino/WMath.cpp
include .build/mega2560/arduino/WMath.d

.build/mega2560/arduino/USBCore.o : /usr/share/arduino/hardware/arduino/cores/arduino/USBCore.cpp
	@echo [93marduino/USBCore.cpp[0m
	@mkdir -p .build/mega2560/arduino
	@/usr/bin/avr-g++ -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=100 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/mega -I/usr/share/arduino/libraries/Servo -Ilib/ros_lib -Ilib/ros_lib/tests -Ilib/ros_lib/ros_rl500xa -Ilib/ros_lib/std_msgs -Ilib/ros_lib/rosserial_msgs -Ilib/ros_lib/ros -Ilib/ros_lib/tf -Ilib/ros_lib/diagnostic_msgs -Ilib/ros_lib/nav_msgs -Ilib/ros_lib/sensor_msgs -Ilib/ros_lib/rosserial_arduino -Ilib/ros_lib/geometry_msgs -Ilib/ros_lib/tests/time_test -Ilib/ros_lib/tests/array_test -Ilib/ros_lib/tests/float64_test -I/usr/share/arduino/hardware/arduino/cores/arduino -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/cores/arduino/USBCore.cpp
include .build/mega2560/arduino/USBCore.d

.build/mega2560/arduino/new.o : /usr/share/arduino/hardware/arduino/cores/arduino/new.cpp
	@echo [93marduino/new.cpp[0m
	@mkdir -p .build/mega2560/arduino
	@/usr/bin/avr-g++ -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=100 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/mega -I/usr/share/arduino/libraries/Servo -Ilib/ros_lib -Ilib/ros_lib/tests -Ilib/ros_lib/ros_rl500xa -Ilib/ros_lib/std_msgs -Ilib/ros_lib/rosserial_msgs -Ilib/ros_lib/ros -Ilib/ros_lib/tf -Ilib/ros_lib/diagnostic_msgs -Ilib/ros_lib/nav_msgs -Ilib/ros_lib/sensor_msgs -Ilib/ros_lib/rosserial_arduino -Ilib/ros_lib/geometry_msgs -Ilib/ros_lib/tests/time_test -Ilib/ros_lib/tests/array_test -Ilib/ros_lib/tests/float64_test -I/usr/share/arduino/hardware/arduino/cores/arduino -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/cores/arduino/new.cpp
include .build/mega2560/arduino/new.d

.build/mega2560/arduino/Print.o : /usr/share/arduino/hardware/arduino/cores/arduino/Print.cpp
	@echo [93marduino/Print.cpp[0m
	@mkdir -p .build/mega2560/arduino
	@/usr/bin/avr-g++ -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=100 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/mega -I/usr/share/arduino/libraries/Servo -Ilib/ros_lib -Ilib/ros_lib/tests -Ilib/ros_lib/ros_rl500xa -Ilib/ros_lib/std_msgs -Ilib/ros_lib/rosserial_msgs -Ilib/ros_lib/ros -Ilib/ros_lib/tf -Ilib/ros_lib/diagnostic_msgs -Ilib/ros_lib/nav_msgs -Ilib/ros_lib/sensor_msgs -Ilib/ros_lib/rosserial_arduino -Ilib/ros_lib/geometry_msgs -Ilib/ros_lib/tests/time_test -Ilib/ros_lib/tests/array_test -Ilib/ros_lib/tests/float64_test -I/usr/share/arduino/hardware/arduino/cores/arduino -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/cores/arduino/Print.cpp
include .build/mega2560/arduino/Print.d

.build/mega2560/arduino/IPAddress.o : /usr/share/arduino/hardware/arduino/cores/arduino/IPAddress.cpp
	@echo [93marduino/IPAddress.cpp[0m
	@mkdir -p .build/mega2560/arduino
	@/usr/bin/avr-g++ -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=100 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/mega -I/usr/share/arduino/libraries/Servo -Ilib/ros_lib -Ilib/ros_lib/tests -Ilib/ros_lib/ros_rl500xa -Ilib/ros_lib/std_msgs -Ilib/ros_lib/rosserial_msgs -Ilib/ros_lib/ros -Ilib/ros_lib/tf -Ilib/ros_lib/diagnostic_msgs -Ilib/ros_lib/nav_msgs -Ilib/ros_lib/sensor_msgs -Ilib/ros_lib/rosserial_arduino -Ilib/ros_lib/geometry_msgs -Ilib/ros_lib/tests/time_test -Ilib/ros_lib/tests/array_test -Ilib/ros_lib/tests/float64_test -I/usr/share/arduino/hardware/arduino/cores/arduino -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/cores/arduino/IPAddress.cpp
include .build/mega2560/arduino/IPAddress.d

.build/mega2560/arduino/WString.o : /usr/share/arduino/hardware/arduino/cores/arduino/WString.cpp
	@echo [93marduino/WString.cpp[0m
	@mkdir -p .build/mega2560/arduino
	@/usr/bin/avr-g++ -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=100 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/mega -I/usr/share/arduino/libraries/Servo -Ilib/ros_lib -Ilib/ros_lib/tests -Ilib/ros_lib/ros_rl500xa -Ilib/ros_lib/std_msgs -Ilib/ros_lib/rosserial_msgs -Ilib/ros_lib/ros -Ilib/ros_lib/tf -Ilib/ros_lib/diagnostic_msgs -Ilib/ros_lib/nav_msgs -Ilib/ros_lib/sensor_msgs -Ilib/ros_lib/rosserial_arduino -Ilib/ros_lib/geometry_msgs -Ilib/ros_lib/tests/time_test -Ilib/ros_lib/tests/array_test -Ilib/ros_lib/tests/float64_test -I/usr/share/arduino/hardware/arduino/cores/arduino -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/cores/arduino/WString.cpp
include .build/mega2560/arduino/WString.d

.build/mega2560/arduino/main.o : /usr/share/arduino/hardware/arduino/cores/arduino/main.cpp
	@echo [93marduino/main.cpp[0m
	@mkdir -p .build/mega2560/arduino
	@/usr/bin/avr-g++ -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=100 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/mega -I/usr/share/arduino/libraries/Servo -Ilib/ros_lib -Ilib/ros_lib/tests -Ilib/ros_lib/ros_rl500xa -Ilib/ros_lib/std_msgs -Ilib/ros_lib/rosserial_msgs -Ilib/ros_lib/ros -Ilib/ros_lib/tf -Ilib/ros_lib/diagnostic_msgs -Ilib/ros_lib/nav_msgs -Ilib/ros_lib/sensor_msgs -Ilib/ros_lib/rosserial_arduino -Ilib/ros_lib/geometry_msgs -Ilib/ros_lib/tests/time_test -Ilib/ros_lib/tests/array_test -Ilib/ros_lib/tests/float64_test -I/usr/share/arduino/hardware/arduino/cores/arduino -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/cores/arduino/main.cpp
include .build/mega2560/arduino/main.d

.build/mega2560/arduino/HardwareSerial.o : /usr/share/arduino/hardware/arduino/cores/arduino/HardwareSerial.cpp
	@echo [93marduino/HardwareSerial.cpp[0m
	@mkdir -p .build/mega2560/arduino
	@/usr/bin/avr-g++ -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=100 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/mega -I/usr/share/arduino/libraries/Servo -Ilib/ros_lib -Ilib/ros_lib/tests -Ilib/ros_lib/ros_rl500xa -Ilib/ros_lib/std_msgs -Ilib/ros_lib/rosserial_msgs -Ilib/ros_lib/ros -Ilib/ros_lib/tf -Ilib/ros_lib/diagnostic_msgs -Ilib/ros_lib/nav_msgs -Ilib/ros_lib/sensor_msgs -Ilib/ros_lib/rosserial_arduino -Ilib/ros_lib/geometry_msgs -Ilib/ros_lib/tests/time_test -Ilib/ros_lib/tests/array_test -Ilib/ros_lib/tests/float64_test -I/usr/share/arduino/hardware/arduino/cores/arduino -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/cores/arduino/HardwareSerial.cpp
include .build/mega2560/arduino/HardwareSerial.d



.build/mega2560/arduino/libarduino.a : .build/mega2560/arduino/wiring_shift.o .build/mega2560/arduino/wiring.o .build/mega2560/arduino/wiring_analog.o .build/mega2560/arduino/WInterrupts.o .build/mega2560/arduino/wiring_digital.o .build/mega2560/arduino/wiring_pulse.o .build/mega2560/arduino/CDC.o .build/mega2560/arduino/HID.o .build/mega2560/arduino/Tone.o .build/mega2560/arduino/Stream.o .build/mega2560/arduino/WMath.o .build/mega2560/arduino/USBCore.o .build/mega2560/arduino/new.o .build/mega2560/arduino/Print.o .build/mega2560/arduino/IPAddress.o .build/mega2560/arduino/WString.o .build/mega2560/arduino/main.o .build/mega2560/arduino/HardwareSerial.o
	@echo [92mLinking libarduino.a[0m
	@/usr/bin/avr-ar rcs $@ $^















.build/mega2560/src/rl_500xa.o : .build/mega2560/src/rl_500xa.cpp
	@echo [93msrc/rl_500xa.cpp[0m
	@mkdir -p .build/mega2560/src
	@/usr/bin/avr-g++ -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=100 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/mega -I/usr/share/arduino/libraries/Servo -Ilib/ros_lib -Ilib/ros_lib/tests -Ilib/ros_lib/ros_rl500xa -Ilib/ros_lib/std_msgs -Ilib/ros_lib/rosserial_msgs -Ilib/ros_lib/ros -Ilib/ros_lib/tf -Ilib/ros_lib/diagnostic_msgs -Ilib/ros_lib/nav_msgs -Ilib/ros_lib/sensor_msgs -Ilib/ros_lib/rosserial_arduino -Ilib/ros_lib/geometry_msgs -Ilib/ros_lib/tests/time_test -Ilib/ros_lib/tests/array_test -Ilib/ros_lib/tests/float64_test -I/usr/share/arduino/hardware/arduino/cores/arduino -fno-exceptions -iquote src  -o $@ -c .build/mega2560/src/rl_500xa.cpp
include .build/mega2560/src/rl_500xa.d







.build/mega2560/firmware.elf : .build/mega2560/src/rl_500xa.o .build/mega2560/Servo/libServo.a .build/mega2560/ros_lib/libros_lib.a .build/mega2560/arduino/libarduino.a
	@echo [92mLinking firmware.elf[0m
	@/usr/bin/avr-gcc -mmcu=atmega2560 -Wl,-Os -Wl,--gc-sections -o $@ $^ -lm


.build/mega2560/firmware.hex : .build/mega2560/firmware.elf
	@echo [92mConverting to firmware.hex[0m
	@/usr/bin/avr-objcopy -O ihex -R .eeprom $^ $@

include .build/mega2560/src/dependencies.d .build/mega2560/arduino/dependencies.d .build/mega2560/Servo/dependencies.d .build/mega2560/ros_lib/dependencies.d

all : .build/mega2560/firmware.hex
	@true

